### ISSUE TITLE
Porting to Linux and Windows 

### ISSUE THREAD

**Issue by JIVS** [mortenjust/freewriter-mac#1]
Are there any plans to do it?

**Comment by mortenjust** [comment]
Not in the near future, I'm afraid.

**Comment by JIVS** [comment]
I don't have a lot of experience with OSX development but looking at the .swift extensions I guess a Linux version could be done relatively easily once swift gets open source later this year.

**Comment by mortenjust** [comment]
Would be interesting to look into that. Not sure how UI views are or will be handled in Linux
